/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/models/iphone/iphone_13_pro.gltf --transform 
Files: ./public/assets/models/iphone/iphone_13_pro.gltf [51.47KB] > /Users/papabaab/Documents/iveez_webapp/react-three-iveez/iphone_13_pro-transformed.glb [153.72KB] (-199%)
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-13-pro-0c34a039d50e42f4b46738ec26929c15
Title: iPhone 13 Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone_13_pro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Frame001_Frame_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Frame001_Mic_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Body002_Wallpaper_0.geometry} material={materials.Wallpaper} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Body002_Camera_Glass_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Body002_Lens_0.geometry} material={materials.Lens} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/iphone_13_pro-transformed.glb')
